@startuml Стратовая диаграмма

participant "Пользователь" as User
participant "Система" as System

User -> System : Данные для входа в личный кабинет
System -> System : Авторизация
System -> User : Перенаправление на страницу \nличного кабинета
User -> System : Выбор предложения
System -> System : Оценка рисков
alt Клиент с высоким риском
    System -> User : К сожалению, мы не готовы выдать кредит
else Клиент с низким риском
    User -> System : Идентификация
    User -> System : Подписание документов
    System -> User : Перед денежных стредств
end



@enduml