@startuml Добавляем опциональные сценарии

title Добавляем опциональные шаги

!include ../../common/settings.puml

== Оценка рисков ==

Client -> Frontend : Выбрал предложение
Frontend -> Backend : POST /application
Backend -> Backend : Создание заявки
opt Если шаг заявки "CREATE"
    alt Заявка создана
        Backend --> Frontend : 200
    else Ошибка сервера
        Backend --> Frontend : 500
        Frontend --> Client : Ошибка: Повторите попытку позже
    end
    Backend --> Scoring : EVENT scoringStart
    Backend -> Backend : Изминить шаг \nзаявки на "Scoring"
end

opt Если шаг заявки "SCORING"
    Scoring -> Scoring : Оценка рисков
    Scoring --> Backend : EVENT scoringFinish
    Backend -> Backend : Сохранение результата
    alt Если результат положительный
        Backend -> Backend : Изминить шаг \nзаявки на "IDENTIFICATION"
    else Иначе
        Backend -> Backend : Изминить шаг \nзаявки на "CLOSED"
    end
end

opt Если шаг заявки "CREATE" или "SCORING"
    Frontend -> Backend : GET /application/{id}
    alt Данные получены
        Backend --> Frontend : 200
    else Ошибка сервера
        Backend --> Frontend : 500
    end
    Frontend -> Client : Отображение результата
end

@enduml