@startuml Создание легенды

title Создание легенды



'__ АКТОРЫ __
actor "Пользователь" as User
participant "Система" as System

'__ ВЗАИМОДЕЙСТВИЕ __
User -> System : HTTP запрос
alt #TECHNOLOGY Успешный ответ
    System --> User : HTTP ответ
else #IMPLEMENTATION Ошибка
    System --> User : HTTP ответ
end

User --> System: Асинхронное взаимодействие


' Легенда
!include legend.puml



'  legend
'  <b>Обозначения цветов</b>
'  <#FFFFFF,#FFFFFF>| <#TECHNOLOGY>   | Успешный исход |
'  | <#IMPLEMENTATION>      | Ошибка выполнения |
'  endlegend


'  legend
'  <b>Обозначения цветов</b>
'  <#FFFFFF,#FFFFFF>| <#TECHNOLOGY>   | Успешный исход |
'  | <#IMPLEMENTATION>      | Ошибка выполнения |
'  endlegend

' legend
' <b>Это легенда</b>
' | стобец 1 | столбе 2 |
' | 1 | 2 |
' | 3 | 4 |
' endlegend

@enduml