@startuml Стратовая диаграмма

title Оценка рисков

!include https://raw.githubusercontent.com/ramdirt/plantuml-course/refs/heads/master/common/settings.puml
!include /common/settings.puml

== Оценка рисков ==

Client -> Frontend : Выбрал предложение $check
Frontend --> Backend : POST /application
return 200
Backend --> Backend : Создание заявки
Backend --> Scoring : EVENT scoringStart
Scoring -> Scoring : Оценка рисков
Scoring --> Backend : EVENT scoringFinish
Backend -> Backend : Сохранение результата
Frontend --> Backend : GET /application
return 200
Frontend -> Client : Отображение результата


@enduml