@startuml Оценка рисков

title Оценка рисков

!include https://raw.githubusercontent.com/ramdirt/plantuml-course/refs/heads/master/common/settings.puml

== Оценка рисков ==

Client -> Frontend : Выбрал предложение
Frontend -> Backend : POST /application
Backend -> Backend : Создание заявки
alt #PHYSICAL Заявка создана
    Backend --> Frontend : 200
else Ошибка сервера
    Backend --> Frontend : 500
    Frontend --> Client : Ошибка: Повторите попытку позже
end
Backend --> Scoring : EVENT scoringStart
Scoring -> Scoring : Оценка рисков
Scoring --> Backend : EVENT scoringFinish
Backend -> Backend : Сохранение результата
alt #PHYSICAL Если заявка создана
    Frontend -> Backend : GET /application/{id}
    alt Данные получены
        Backend --> Frontend : 200
    else Ошибка сервера
        Backend --> Frontend : 500
    end
    Frontend -> Client : Отображение результата
end

@enduml