@startuml Широкая диаграмма

title Подробное описание

'__ АКТОРЫ __
actor "Клиент" as Client
participant "Фронтэнд" as Frontend
participant "API Gateway" as API_Gateway
box "Сервис клиентов"
    participant "Сервис клиентов" as Service_Clients
    database "БД" as DB_Clients
end box
queue "Кафка" as Kafka
box "Сервис документов"
    participant "Сервис Документов" as Service_Documents
    database "БД" as DB_Documents
end box
database "Общий S3" as S3

'__ ВЗАИМОДЕЙСТВИЕ __
== Создание клиента ==
Client -> Frontend : Регистрация
Frontend -> API_Gateway : POST /clients
API_Gateway -> API_Gateway : Авторизация запроса
API_Gateway -> Service_Clients: POST /clients
Service_Clients-> DB_Clients : INSERT clients
DB_Clients --> Service_Clients : Сохранено
Service_Clients --> Frontend : 200 Клиент создан
Frontend -> Frontend : Переход на страницу \nпросмотра документов 

== Генерация документов ==
Service_Clients-> Kafka : PUSH EVENT DocumentsGenerate
Service_Documents -> Kafka : PULL EVENT DocumentsGenerate
Service_Documents -> Service_Documents : Генерация документов
Service_Documents -> S3 : Сохранение документов
return Сохранено
Service_Documents -> DB_Documents : INSERT documents
return Сохранено


== Получение документов ==
opt Если клиент зарегестрирован
    loop Каждые 3 секунды
        Frontend -> API_Gateway : GET /users/{user_id}/documents
        API_Gateway -> API_Gateway : Авторизация запроса
        API_Gateway -> Service_Documents : GET /users/{user_id}/documents
        Service_Documents -> DB_Documents : SELECT documents
        alt Документы существуют
            DB_Documents --> Service_Documents : Список записей
            Service_Documents -> S3 : Запрос предподписанных \nссылок на документы
            S3 --> Service_Documents : Предподписанные ссылки
            Service_Documents --> Frontend : 200
            Frontend --> Client : Документы для подписи
        else Документов нет
            DB_Documents --> Service_Documents : Нет записей
            Service_Documents --> Frontend : 404
            Frontend --> Client : Ожидайте, документы генерируются
        end
    end
end

@enduml