@startuml Широкая диаграмма

title Убираем лишние взаимодействие gateway и kafka

'__ АКТОРЫ __
actor "Клиент" as Client
participant "Фронтэнд" as Frontend
participant "Сервис клиентов" as Service_Clients
participant "Сервис Документов" as Service_Documents

'__ ВЗАИМОДЕЙСТВИЕ __
== Создание клиента ==
Client -> Frontend : Регистрация
Frontend -> Service_Clients: POST /users
Service_Clients-> Service_Clients : <b>Создание клиента</b> \nв таблице clients
Service_Clients --> Frontend : 200 Клиент создан
Frontend -> Frontend : Переход на страницу \nпросмотра документов 

== Генерация документов ==
Service_Clients --> Service_Documents: EVENT DocumentsGenerate
Service_Documents -> Service_Documents : Генерация документов
Service_Documents -> Service_Documents : Сохранение документов на S3
Service_Documents -> Service_Documents : Сохранение документов \nв таблице documents


== Получение документов ==
opt Если клиент зарегестрирован
    loop Каждые 3 секунды
        Frontend -> Service_Documents : GET /users/{user_id}/documents
        Service_Documents -> Service_Documents : Получение документов из таблицы documents
        alt Документы существуют
            Service_Documents -> Service_Documents : Получение предподписанных \nссылок на S3
            Service_Documents --> Frontend : 200
            Frontend --> Client : Документы для подписи
        else Документов нет
            Service_Documents --> Frontend : 404
            Frontend --> Client : Ожидайте, документы генерируются
        end
    end
end

@enduml