@startuml Широкая диаграмма

title Для бизнеса

'__ АКТОРЫ __
actor "Клиент" as Client
participant "Наша система" as System

'__ ВЗАИМОДЕЙСТВИЕ __
Client -> System : Клиент отправляет \nформу регистрации
System -> System : Создание и сохранение клиента
System -> System : Создание и \nсохранение документов
alt Документы созданы
    System -> Client : Отображение списка документов
else Документов нет, они генерируются
    System -> Client : Отображение экрана ожидания
end


@enduml