@startuml Широкая диаграмма

title Для интеграций с внешними компаниями

'__ АКТОРЫ __
participant External_Сompany as "Внешняя компания"

box "Ваша компания"
    participant API as "API"
end box

'__ ВЗАИМОДЕЙСТВИЕ __
== Проверка наличия клиента==
External_Сompany -> API : GET /client/{client_phone}
alt Клиент не существует
    ||7||
    ref over External_Сompany, API : Создание клиента
else Клиент существует
    ||7||
    ref over External_Сompany, API : Создание заявки на кредит
end



@enduml