
'хороший пример
@startuml Хороший пример

title Хороший пример

participant Frontend
participant Backend

loop
    Frontend -> Backend: GET application/{id}
    Backend -> Frontend: 200 {stage: {Шаг заявки}}

    alt Есть активный кредит
        Frontend -> Client: Показать страницу "UI_9: Активный кредит"
    else Нет активного кредита
        Frontend -> Client: Показать страницу "UI_1: Главная"
    end
end

@enduml


'плохой пример
@startuml Плохой пример
participant Frontend
participant Backend
loop
    Frontend -> Backend: GET application/{id}
    Backend -> Frontend: 200 {stage: {Шаг заявки}}
    alt Есть активный кредит
        Frontend -> Client: Показать страницу "UI_9: Активный кредит"
    else Нет активного кредита
        Frontend -> Client: Показать страницу "UI_1: Главная"
    end
end
@enduml



