@startuml Взаимодействие

title Синхронное и асинхронное взаимодействие

<style>
document {
  Margin 50
}
</style>
hide unlinked
skinparam ParticipantPadding 50
'__ АКТОРЫ __
actor "Пользователь" as User
participant "Система" as System

||50||

User -> System: Выбрал предложение


||50||


@enduml